baseURL = "https://thibaultlebrun.dev/"
languageCode = "en"
defaultContentLanguage = "en"                             # en / zh-cn / ... (This field determines which i18n file to use)
title = "Home"
preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = false # disabled for Vercel deployment (no git repo in build)
summaryLength  = 0

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

[pagination]
  pagerSize = 50
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = ""            # default: author.name

[author]                  # essential
  name = "Thibault Lebrun"

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

#sectionPagesMenu = "main"
#[[menu.main]]
#  title = "Blog content"
#  name = "Blog content"
#  weight = 40
#  identifier = "blog"
#  url = "/post/"

[params]
  debug = false

  since = "2021"            # Site creation time
  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  gitRepo = ""

  # site info (optional)
  logoTitle = ""        # default: the title value
  keywords = ["web development", "fullstack", "backend", "Python", "Node.js", "freelance", "MVP"]
  subtitle = ""
  description = "Senior fullstack/backend web developer (10 years of experience). I design and develop modern web platforms and robust backends in Python or Node.js. Specialized in creating MVPs and medium-complexity web platforms."

  # paginate of archives, tags and categories
  archivePaginate = 50

  # show 'xx Posts In Total' in archive page ?
  showArchiveCount = false

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?
  moreMeta = true

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.

  uglyURLs = false          # please keep same with uglyurls setting

  # Show language selector for multilingual site.
  showLanguageSelector = false

  [params.social]
    a-github = "https://github.com/lebrunthibault"
    b-linkedin = "https://www.linkedin.com/in/thibault-lebrun/"
    c-link = "https://www.malt.fr/profile/thibaultlebrun"
    d-email = "mailto:thibaultlebrun@live.fr"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# see https://gohugo.io/getting-started/configuration-markup
[markup]
  [markup.goldmark.renderer]
    unsafe = true

# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffixes = ["md"]
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
[outputs]
home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
